steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/testnetcore-307711/api-ci-cd', '.']
  # push the container image to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/testnetcore-307711/api-ci-cd']
  # deploy container image to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'api-ci-cd', '--image', 'gcr.io/testnetcore-307711/api-ci-cd', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/testnetcore-307711/api-ci-cd